Repository oktadev/okta-blog, pull requests merged in 2021-03, with the labels that each got.

#624 Update React Native Login to use CLI
  _source/_assets/img/blog/react-native-login/add-auth-process.png
  _source/_assets/img/blog/react-native-login/android-avd.png
  _source/_assets/img/blog/react-native-login/android-id-token-scotch.png
  _source/_assets/img/blog/react-native-login/android-id-token.png
  _source/_assets/img/blog/react-native-login/android-login-process.png
  _source/_assets/img/blog/react-native-login/ios-login-complete.png
  _source/_assets/img/blog/react-native-login/ios-login-process.png
  _source/_assets/img/blog/react-native-login/ios-okta-login.png
  _source/_assets/img/blog/react-native-login/react-native-login.png
  _source/_includes/setup/cli.md
  _source/_posts/2019-11-14-react-native-login.md
Labels: qa-complete

#627 Update Reactive JHipster for v7 and to use CLI
  README.md
  _source/_assets/css/asciidoctor.css
  _source/_assets/img/blog/reactive-java-microservices/e2e-success.png
  _source/_assets/img/blog/reactive-java-microservices/jhipster-colors.png
  _source/_assets/img/blog/reactive-java-microservices/jhipster-command.png
  _source/_assets/img/blog/reactive-java-microservices/keycloak-login.png
  _source/_includes/setup/cli.md
  _source/_posts/2021-01-20-reactive-java-microservices.adoc
Labels: qa-complete

#625 Update Spring Boot + JUnit 5 to use CLI
  _source/_includes/setup/oidcdebugger.md
  _source/_posts/2019-03-28-test-java-spring-boot-junit5.md
Labels: qa-complete

#633 Update Auth JS + PKCE post to use CLI for setup
  _source/_posts/2019-08-22-okta-authjs-pkce.md
Labels: qa-needed

#600 Update 2017-03-30-react-okta-sign-in-widget.md
  _source/_posts/2017-03-30-react-okta-sign-in-widget.md
Labels: javascript

#634 Update Angular MySQL post to use CLI for setup
  _source/_posts/2019-08-16-angular-mysql-express.md
Labels: qa-complete

#612 Update Vue Login post to use CLI for setup
  _source/_includes/setup/cli.md
  _source/_posts/2020-05-15-vue-login.md
Labels: qa-complete
