Repository oktadev/okta-blog, pull requests merged in 2021-04, with the labels that each got.

#648 Update Java Token Auth post to use CLI for setup
  _source/_assets/img/blog/java-token-auth/add-scope.png
  _source/_assets/img/blog/java-token-auth/client-credentials.png
  _source/_assets/img/blog/java-token-auth/client-id-secret.png
  _source/_assets/img/blog/java-token-auth/create-new-app.png
  _source/_posts/2018-10-16-token-auth-for-java.md
Labels: qa-complete

#619 Update React Login post to use CLI for setup
  _source/_posts/2020-12-16-react-login.md
Labels: qa-complete

#638 Update React Native App Store post to use CLI for setup
  _source/_posts/2019-04-05-react-native-ios-app-store.md
Labels: qa-complete

#617 Update Spring Cloud Config post to use CLI for setup
  _source/_posts/2020-12-07-spring-cloud-config.md
Labels: qa-complete

#613 Update React Hooks post to use CLI for setup
  README.md
  _source/_posts/2020-08-26-react-hooks.md
  _source/blog/setup.md
Labels: qa-complete

#643 Update Spring PreAuthorize post to use CLI for setup
  _source/_assets/img/blog/spring-preauthorize/add-app.png
  _source/_assets/img/blog/spring-preauthorize/add-scope.png
  _source/_assets/img/blog/spring-preauthorize/auth-server-claims.png
  _source/_assets/img/blog/spring-preauthorize/claims.png
  _source/_assets/img/blog/spring-preauthorize/edit-claim.png
  _source/_assets/img/blog/spring-preauthorize/new-oidc-app.png
  _source/_posts/2019-06-20-spring-preauthorize.md
Labels: java, qa-complete

#649 Update Spring Boot JPA post to use CLI for setup
  _source/_posts/2018-12-13-build-basic-app-spring-boot-jpa.md
Labels: qa-complete

#652 Update Angular Webpack post to use CLI for setup
  _source/_posts/2019-12-09-angular-webpack.md
Labels: qa-complete

#674 Updates Docker + Spring Boot post to use CLI for setup
  _source/_posts/2019-12-27-spring-boot-deploy-docker.adoc
Labels: qa-complete

#660 Update Spring Boot Docker post to use CLI to setup
  _source/_posts/2020-12-28-spring-boot-docker.md
Labels: qa-complete

#644 Update Offline JWT Validation with Go setup to use the Okta CLI.
  _source/_posts/2021-01-04-offline-jwt-validation-with-go.md
Labels: qa-complete

#641 Update 2021-02-26-unity-webgl-playfab-authorization.md
  _source/_posts/2021-02-26-unity-webgl-playfab-authorization.md
Labels: qa-complete

#676 Update CLI with Node.js to use CLI for setup
  _source/_assets/img/blog/command-line-apps-with-nodejs/okta-01-sign-up.png
  _source/_assets/img/blog/command-line-apps-with-nodejs/okta-02-create-app.png
  _source/_assets/img/blog/command-line-apps-with-nodejs/okta-03-native-app.png
  _source/_assets/img/blog/command-line-apps-with-nodejs/okta-04-app-settings.png
  _source/_assets/img/blog/command-line-apps-with-nodejs/okta-05-select-app.png
  _source/_assets/img/blog/command-line-apps-with-nodejs/okta-06-client-id.png
  _source/_assets/img/blog/command-line-apps-with-nodejs/okta-07-org-url.png
  _source/_includes/setup/cli.md
  _source/_posts/2019-06-18-command-line-app-with-nodejs.md
  _source/blog/setup.md
Labels: qa-complete

#686 Update Flask React post to use CLI for setup
  _source/_assets/img/blog/python-react/app-login-button.png
  _source/_assets/img/blog/python-react/app-login.png
  _source/_assets/img/blog/python-react/okta-add-application.png
  _source/_assets/img/blog/python-react/okta-choose-spa.png
  _source/_assets/img/blog/python-react/okta-developer-signup.png
  _source/_assets/img/blog/python-react/okta-spa-settings.png
  _source/_assets/img/blog/python-react/react-app-first-run.png
  _source/_assets/img/blog/python-react/start-script.png
  _source/_includes/setup/cli.md
  _source/_posts/2018-12-20-crud-app-with-python-flask-react.md
Labels: qa-complete

#687 Update Node React post to use CLI for setup
  _source/_assets/img/blog/node-react-crud/create-new-application-settings.png
  _source/_posts/2018-07-10-build-a-basic-crud-app-with-node-and-react.md
Labels: qa-complete

#677 Update Node Token Auth to use CLI for setup
  .gitignore
  _source/_assets/img/blog/node-token-auth/okta-app-settings.png
  _source/_assets/img/blog/node-token-auth/okta-create-app.png
  _source/_assets/img/blog/node-token-auth/okta-create-scope.png
  _source/_posts/2019-02-14-modern-token-authentication-in-node-with-express.md
Labels: qa-complete

#655 Update Android Play Store post to use CLI for setup
  _source/_posts/2018-12-26-react-native-android-play-store.md
Labels: qa-complete

#680 Update Node SQL Server to use CLI for setup
  _source/_assets/img/blog/node-sql-server/okta-01-sign-up.jpg
  _source/_assets/img/blog/node-sql-server/okta-02-add-app.jpg
  _source/_assets/img/blog/node-sql-server/okta-03-create-web-app.jpg
  _source/_assets/img/blog/node-sql-server/okta-04-app-settings.jpg
  _source/_assets/img/blog/node-sql-server/okta-05-client-credentials.jpg
  _source/_assets/img/blog/node-sql-server/okta-06-org-url.jpg
  _source/_assets/img/blog/node-sql-server/okta-07-users-registration.jpg
  _source/_assets/img/blog/node-sql-server/okta-08-enable-self-service-registration.jpg
  _source/_posts/2019-03-11-node-sql-server.md
Labels: qa-complete

#673 Update Angular 9 + Spring boot 2.2 post to use CLI for setup
  _source/_assets/img/blog/spring-boot-2-angular-9/angular9-oidc-settings.png
  _source/_assets/img/blog/spring-boot-2-angular-9/spring-boot-oidc-settings.png
  _source/_posts/2020-01-06-crud-angular-9-spring-boot-2.adoc
Labels: qa-complete

#665 Update Angular Docker Spring Boot post for the Okta Admin Console
  _source/_posts/2020-06-17-angular-docker-spring-boot.adoc
Labels: qa-complete

#683 Update Node REST API post to use CLI for setup
  _source/_assets/img/blog/rest-api-node/adding-scope.png
  _source/_assets/img/blog/rest-api-node/issuer.png
  _source/_includes/setup/cli.md
  _source/_posts/2018-08-21-build-secure-rest-api-with-node.md
Labels: qa-complete

#670 Update Angular Bootstrap post to use CLI for setup
  _source/_posts/2020-03-02-angular-bootstrap.adoc
Labels: qa-complete

#682 Update .NET Angular post to use CLI for setup
  _source/_assets/img/blog/mvc-angular/okta-add-spa.png
  _source/_assets/img/blog/mvc-angular/okta-app-settings.png
  _source/_assets/img/blog/mvc-angular/okta-client-credentials.png
  _source/_assets/img/blog/mvc-angular/okta-org-url.png
  _source/_assets/img/blog/mvc-angular/okta-signup.png
  _source/_posts/2018-12-21-build-basic-web-app-with-mvc-angular.md
Labels: qa-complete

#656 Update MicroProfile GraphQL post to use CLI for setup
  _source/_assets/img/blog/microprofile-graphql/add-oidc-app.png
  _source/_assets/img/blog/microprofile-graphql/groups-claim.png
  _source/_posts/2021-01-11-microprofile-graphql.md
Labels: qa-complete

#653 Update Kafka Microservices post to use CLI for setup
  _source/_posts/2020-01-22-kafka-microservices.md
Labels: qa-complete

#685 Update Decode JWT C# post to use CLI for setup
  _source/_posts/2019-06-26-decode-jwt-in-csharp-for-authorization.md
Labels: qa-complete

#667 Update CSS Grid + React post to use CLI for setup
  _source/_assets/img/blog/css-grid-react/okta-create-spa-choice.png
  _source/_assets/img/blog/css-grid-react/okta-react-settings.png
  _source/_posts/2020-08-19-css-grid-react.md
Labels: qa-needed

#689 Update Angular Node post to use CLI for setup
  _source/_assets/img/blog/angular-node/add-application.png
  _source/_assets/img/blog/angular-node/developer.okta.com.png
  _source/_assets/img/blog/angular-node/my-angular-app.png
  _source/_assets/img/blog/angular-node/single-page-app.png
  _source/_assets/img/blog/angular-node/start-building.png
  _source/_posts/2018-10-30-basic-crud-angular-and-node.md
Labels: qa-complete

#688 Update Spring Boot Tomcat post to use CLI for setup
  _source/_assets/img/blog/spring-boot-tomcat/spring-initializr.png
  _source/_posts/2019-04-16-spring-boot-tomcat.md
Labels: qa-complete

#654 Update Spring Boot 15min to use CLI for setup
  _source/_assets/img/blog/spring-boot-user-auth/add-claim.png
  _source/_assets/img/blog/spring-boot-user-auth/classic-ui.png
  _source/_assets/img/blog/spring-boot-user-auth/client-id-and-secret.png
  _source/_assets/img/blog/spring-boot-user-auth/create-new-app.png
  _source/_assets/img/blog/spring-boot-user-auth/directory-registration.png
  _source/_assets/img/blog/spring-boot-user-auth/groups-with-admin.png
  _source/_assets/img/blog/spring-boot-user-auth/groups.png
  _source/_assets/img/blog/spring-boot-user-auth/oidc-app.png
  _source/_assets/img/blog/spring-boot-user-auth/self-service-registration.png
  _source/_posts/2018-10-05-build-a-spring-boot-app-with-user-authentication.md
Labels: qa-complete

#684 Update Node + Vue post to use CLI for setup
  _source/_assets/img/blog/vue-crud-node/add-application.png
  _source/_assets/img/blog/vue-crud-node/new-application-options.png
  _source/_assets/img/blog/vue-crud-node/okta-application-settings.png
  _source/_assets/img/blog/vue-crud-node/okta-developer-sign-up.png
  _source/_posts/2018-02-15-build-crud-app-vuejs-node.md
Labels: qa-complete

#611 Update PHP REST API post to use CLI for setup
  _source/_posts/2019-03-08-simple-rest-api-php.md
Labels: qa-complete

#661 Update Vaadin Spring Boot post to use CLI for setup
  _source/_assets/img/blog/vaadin-spring-boot/select-spa.png
  _source/_assets/img/blog/vaadin-spring-boot/spa-settings.png
  _source/_posts/2020-11-09-vaadin-spring-boot.adoc
Labels: qa-complete

#662 Update Ktor post to use CLI for setup
  _source/_assets/img/blog/ktor-kotlin/enable-okta-user-registrations.png
  _source/_assets/img/blog/ktor-kotlin/okta-add-person.png
  _source/_assets/img/blog/ktor-kotlin/okta-client-id-and-client-secret.png
  _source/_assets/img/blog/ktor-kotlin/okta-configure-application-for-ktor.png
  _source/_assets/img/blog/ktor-kotlin/okta-create-new-web-application.png
  _source/_posts/2020-10-19-ktor-kotlin.md
Labels: qa-complete

#666 Update Spring Boot Heroku post for new Okta Admin Console
  _source/_assets/img/blog/spring-boot-heroku/okta-enable-registration-configuration.png
  _source/_posts/2020-08-31-spring-boot-heroku.md
Labels: qa-complete

#658 Update Spring Cloud Gateway Patterns to use CLI for setup
  _source/_assets/img/blog/spring-gateway-patterns/pricing-scope.png
  _source/_posts/2020-08-14-spring-gateway-patterns.md
Labels: qa-complete

#663 Update Heroku Docker React post to use CLI for setup
  _source/_assets/img/blog/react-docker/okta-app-settings.png
  _source/_posts/2020-06-24-heroku-docker-react.md
Labels: qa-complete

#703 Update Spring Boot + Vue post to use CLI for setup
  _source/_assets/img/blog/spring-boot-vue/oidc-app-settings.png
  _source/_posts/2020-06-26-spring-boot-vue-kotlin.md
Labels: qa-complete

#664 Update Node.js Login post to use CLI for setup
  _source/_includes/setup/cli.md
  _source/_posts/2020-06-16-nodejs-login.adoc
Labels: qa-complete

#668 Update Serverless Java post to use CLI for setup
  _source/_assets/img/blog/serverless-java-aws/okta-oidc-application.png
  _source/_includes/setup/oidcdebugger.md
  _source/_posts/2020-05-27-serverless-java-aws.md
Labels: qa-complete

#669 Update Android Authentication post to use CLI for setup
  _source/_assets/img/blog/android-authentication/okta-create-new-application.jpg
  _source/_includes/setup/cli.md
  _source/_posts/2020-04-20-android-authentication.adoc
Labels: qa-complete

#671 Update Gatsby React post to use CLI for setup
  _source/_assets/img/blog/gatsby-netlify-okta/1st-post.png
  _source/_assets/img/blog/gatsby-netlify-okta/admin.png
  _source/_assets/img/blog/gatsby-netlify-okta/blog-added.png
  _source/_assets/img/blog/gatsby-netlify-okta/blogroll.png
  _source/_assets/img/blog/gatsby-netlify-okta/create-post.png
  _source/_assets/img/blog/gatsby-netlify-okta/gatsby-netlify.png
  _source/_assets/img/blog/gatsby-netlify-okta/hello-world.png
  _source/_assets/img/blog/gatsby-netlify-okta/login.png
  _source/_assets/img/blog/gatsby-netlify-okta/netlify-create.png
  _source/_assets/img/blog/gatsby-netlify-okta/netlify-deploy-inprogress.png
  _source/_assets/img/blog/gatsby-netlify-okta/netlify-deploy-settings.png
  _source/_assets/img/blog/gatsby-netlify-okta/netlify-deploy-summary.png
  _source/_assets/img/blog/gatsby-netlify-okta/netlify-deployed.png
  _source/_assets/img/blog/gatsby-netlify-okta/netlify-find-github-app.png
  _source/_assets/img/blog/gatsby-netlify-okta/netlify-start.png
  _source/_assets/img/blog/gatsby-netlify-okta/okta-app-settings.png
  _source/_assets/img/blog/gatsby-netlify-okta/okta-authenticated.png
  _source/_assets/img/blog/gatsby-netlify-okta/okta-create-account.png
  _source/_assets/img/blog/gatsby-netlify-okta/okta-signin.png
  _source/_assets/img/blog/gatsby-netlify-okta/okta-signup.png
  _source/_assets/img/blog/gatsby-netlify-okta/okta-trusted-origins.png
  _source/_assets/img/blog/gatsby-netlify-okta/register-github-app.png
  _source/_posts/2020-02-18-gatsby-react-netlify.md
Labels: qa-complete

#708 Update Java GraphQL post to use CLI
  _source/_includes/setup/maven.md
  _source/_posts/2020-01-31-java-graphql.md
Labels: qa-complete

#707 Update Schematics posts to use CLI
  README.md
  _source/_assets/img/blog/angular-schematics/hello-matt.png
  _source/_assets/img/blog/angular-schematics/login-with-arrow.png
  _source/_assets/img/blog/angular-schematics/login.png
  _source/_assets/img/blog/angular-schematics/ng-add-@oktadev-schematics.png
  _source/_assets/img/blog/angular-schematics/oidc-app-settings.png
  _source/_assets/img/blog/angular-schematics/signup.png
  _source/_assets/img/blog/react-schematics/app-settings.png
  _source/_assets/img/blog/react-schematics/create-react-app.png
  _source/_assets/img/blog/react-schematics/react-okta.png
  _source/_assets/img/blog/vue-schematics/okta-oidc-settings.png
  _source/_assets/img/blog/vue-schematics/vue-cli-features.png
  _source/_assets/img/blog/vue-schematics/vue-with-bootstrap.png
  _source/_posts/2019-02-13-angular-schematics.adoc
  _source/_posts/2019-03-05-react-schematics.md
  _source/_posts/2019-05-21-vue-schematics.md
  package.json
  scripts/dev-clean.js
Labels: qa-complete

#710 Update Java SSO post for new Admin Console
  _source/_posts/2020-01-29-java-single-sign-on.md
Labels: qa-complete

#759 Update Angular PWA post to use Angular 11 use CLI for setup
  _source/_assets/img/blog/first-angular-pwa/developer.okta.com.png
  _source/_assets/img/blog/first-angular-pwa/lighthouse-46.png
  _source/_assets/img/blog/first-angular-pwa/lighthouse-pwa.png
  _source/_assets/img/blog/first-angular-pwa/lighthouse-score.png
  _source/_assets/img/blog/first-angular-pwa/new-app.png
  _source/_assets/img/blog/first-angular-pwa/okta-applications.png
  _source/_posts/2019-01-30-first-angular-pwa.md
Labels: qa-complete

#678 Update .NET Token Auth to use CLI for setup
  _source/_assets/img/blog/webapi-token-auth/AddApplication.png
  _source/_assets/img/blog/webapi-token-auth/ApplicationGeneralSettings.png
  _source/_assets/img/blog/webapi-token-auth/CreateServiceScreen.png
  _source/_assets/img/blog/webapi-token-auth/DefaultAuthorizationServer.png
  _source/_assets/img/blog/webapi-token-auth/NameServiceScreen.png
  _source/_posts/2018-02-01-secure-aspnetcore-webapi-token-auth.md
Labels: qa-needed

#764 update secure-web-apps-websockets-nodejs
  _source/_assets/img/blog/secure-web-apps-websockets-nodejs/okta-app-settings.png
  _source/_posts/2020-10-28-secure-web-apps-websockets-nodejs.md
Labels: qa-complete

#672 Update Angular Ivy post to use CLI for setup
  _source/_posts/2020-02-12-angular-ivy.md
Labels: qa-complete

#711 Update Java REST API for new Admin Console
  _source/_assets/img/blog/java-rest-api/client-credentials.png
  _source/_assets/img/blog/java-rest-api/okta-homepage.png
  _source/_assets/img/blog/java-rest-api/okta-maven-app.png
  _source/_assets/img/blog/java-rest-api/okta-new-app.png
  _source/_posts/2020-01-09-java-rest-api-showdown.md
Labels: qa-complete

#712 Update Java Jersey post to use CLI
  _source/_assets/img/blog/java-jersey-jaxrs/okta-applications.png
  _source/_includes/setup/oidcdebugger.md
  _source/_posts/2019-12-30-java-jersey-jaxrs.adoc
Labels: qa-needed

#713 Update Java MongoDB post to use CLI
  _source/_assets/img/blog/java-mongodb-crud/issuer.png
  _source/_assets/img/blog/java-mongodb-crud/oidc-settings.png
  _source/_posts/2019-12-26-java-mongodb-crud.md
Labels: qa-complete

#714 Update React Sass to use CLI
  _source/_assets/img/blog/react-sass/okta-settings.png
  _source/_assets/img/blog/react-sass/okta-spa.png
  _source/_posts/2019-12-17-react-sass.md
Labels: qa-complete

#715 Update Kotlin Guide to use CLI
  _source/_posts/2019-12-12-tutorial-kotlin-beginners-guide.md
Labels: qa-complete

#716 Update Spring Boot Deploy post to use CLI for setup
  _source/_posts/2019-12-03-spring-boot-deploy-options.md
  _source/blog/setup.md
Labels: qa-needed

#717 Update Java Netty WebFlux post to use CLI for setup
  _source/_assets/img/blog/java-netty-webflux/new-okta-app.png
  _source/_posts/2019-11-25-java-netty-webflux.md
Labels: qa-complete

#718 Update Java Kafka post to use CLI for setup
  _source/_assets/img/blog/kafka-java/client-credentials.png
  _source/_assets/img/blog/kafka-java/okta-applications.png
  _source/_posts/2019-11-19-java-kafka.md
Labels: qa-needed

#719 Update GraphQL Vue post to use CLI for setup
  _source/_assets/img/blog/graphql-vue-olympics/okta-settings.png
  _source/_posts/2019-11-11-graphql-vue.md
Labels: qa-complete

#721 Update Java OAuth 2.0 post to use CLI for setup
  _source/_assets/img/blog/java-oauth2/okta-applications.png
  _source/_posts/2019-10-30-java-oauth2.md
Labels: qa-needed

#720 Update Java Jetty post to use CLI for setup
  _source/_assets/img/blog/java-jetty/issuer-uri.png
  _source/_posts/2019-11-07-java-jetty-oauth.md
Labels: qa-needed

#722 Update Android Gradle post to use CLI for setup
  _source/_posts/2019-10-25-intro-android-gradle.md
Labels: qa-complete

#723 Update Java WebSocket post to use CLI for setup
  _source/_posts/2019-10-09-java-spring-websocket-tutorial.md
Labels: qa-complete

#724 Update Quarkus OIDC post to use CLI for setup
  _source/_assets/img/blog/java-quarkus-oidc/add-groups-claim.png
  _source/_posts/2019-09-30-java-quarkus-oidc.md
Labels: qa-complete

#725 Update JSF post to use CLI for setup
  _source/_posts/2019-09-27-build-crud-app-jsf.md
Labels: qa-complete

#726 Update ELK Stack post to use CLI for setup
  _source/_posts/2019-09-26-get-started-elk-stack.md
Labels: qa-complete

#727 Update Spring Boot Kotlin post to use CLI for setup
  _source/_assets/img/blog/build-a-spring-boot-kotlin-app/okta-new-applicaiton.png
  _source/_posts/2019-09-17-build-a-spring-boot-kotlin-app.md
Labels: qa-complete

#728 Update Gradle Tutorial post to use CLI for setup
  _source/_assets/img/blog/gradle-tutorial/create-okta-application.png
  _source/_posts/2019-09-03-gradle-tutorial.md
Labels: qa-complete

#729 Update Spring Cloud Gateway post to use Maven include
  _source/_includes/setup/maven.md
  _source/_posts/2019-08-28-reactive-microservices-spring-cloud-gateway.adoc
Labels: qa-complete

#730 Update Groovy Tests post to use CLI for setup
  _source/_posts/2019-08-21-make-java-tests-groovy.md
Labels: qa-complete

#731 Updates Jib + Spring Boot post to use CLI for setup
  _source/_posts/2019-08-09-jib-docker-spring-boot.md
Labels: qa-complete

#732 Updates AWS Beanstalk post to use CLI for setup
  _source/_assets/img/blog/spring-boot-aws/okta-aws-ebs-05.png
  _source/_posts/2019-08-07-deploy-a-spring-boot-app-with-aws-elastic-beanstalk.md
Labels: qa-complete

#733 Update Servlet Auth post to use the new Admin Console
  _source/_assets/img/blog/servlet-authentication/add-person.png
  _source/_posts/2019-07-22-servlet-authentication.md
Labels: qa-complete

#734 Update Spring Boot Actuator post to use CLI for setup
  _source/_posts/2019-07-17-monitoring-with-actuator.md
Labels: qa-complete

#735 Update MicroProfile JWT post to use CLI for setup
  _source/_assets/img/blog/microprofile-jwt-auth/add-groups-claim.png
  _source/_assets/img/blog/microprofile-jwt-auth/oidc-web-app.png
  _source/_posts/2019-07-10-java-microprofile-jwt-auth.md
Labels: qa-complete

#736 Update Spring Boot + MySQL post to use CLI for setup
  _source/_posts/2019-07-03-spring-boot-jpa.md
Labels: qa-complete

#737 Update Ionic JHipster post to use CLI for setup
  _source/_assets/img/blog/ionic-4-jhipster/claims.png
  _source/_posts/2019-06-24-ionic-4-angular-spring-boot-jhipster.adoc
Labels: qa-complete

#738 Update Ionic 4 post to use CLI for setup
  _source/_assets/img/blog/ionic-4-login/add-application.png
  _source/_assets/img/blog/ionic-4-login/enable-registration.png
  _source/_assets/img/blog/ionic-4-login/ionic-4-client-credentials.png
  _source/_assets/img/blog/ionic-4-login/ionic-4-login-redirect-uris.png
  _source/_assets/img/blog/ionic-4-login/ionic-4-logout-redirect-uris.png
  _source/_assets/img/blog/ionic-4-login/issuer-uri.png
  _source/_assets/img/blog/ionic-4-login/new-native-app.png
  _source/_assets/img/blog/ionic-4-login/registration-settings.png
  _source/_assets/img/blog/ionic-4-login/user-registration.png
  _source/_posts/2019-06-20-ionic-4-tutorial-user-authentication-and-registration.md
Labels: qa-complete

#739 Update Spring Security Auth post to use CLI for setup
  _source/_assets/img/blog/spring-boot-authentication/dashboard-applications.png
  _source/_posts/2019-05-31-spring-security-authentication.md
Labels: qa-complete

#740 Update Vue PWA post to use CLI for setup
  _source/_assets/img/blog/vue-pwa/create-new-app.png
  _source/_posts/2019-05-30-vue-pwa-typescript.md
Labels: qa-complete

#741 Update Angular JWT post to use CLI for setup
  _source/_assets/img/blog/jwt-angular/angular-spa-okta-settings.png
  _source/_assets/img/blog/jwt-angular/new-app.png
  _source/_posts/2019-05-16-angular-authentication-jwt.md
Labels: qa-complete

#742 Update Spring Boot Login Options post to use CLI for setup
  _source/_assets/img/blog/spring-boot-login-options/enable-registration.png
  _source/_assets/img/blog/spring-boot-login-options/oidc-settings.png
  _source/_assets/img/blog/spring-boot-login-options/user-registration.png
  _source/_posts/2019-05-15-spring-boot-login-options.md
Labels: qa-complete

#743 Updates Angular MVC post to use CLI for setup
  _source/_assets/img/blog/angular-mvvm-pattern/applications-developer.okta.com.png
  _source/_assets/img/blog/angular-mvvm-pattern/new-app-developer.okta.com.png
  _source/_posts/2019-04-26-angular-mvc-primer.md
Labels: qa-complete

#744 Update Spring Security Testing post to use CLI for setup
  _source/_assets/img/blog/testing-jhipster-6/add-claim.png
  _source/_assets/img/blog/testing-jhipster-6/app-settings.png
  _source/_includes/setup/cli.md
  _source/_posts/2019-04-15-testing-spring-security-oauth-with-junit.adoc
Labels: qa-complete

#746 Update Spring Boot Kubernetes post to use CLI for setup
  _source/_assets/img/blog/spring-boot-kubernetes/create-new-application.png
  _source/_assets/img/blog/spring-boot-kubernetes/oidc-application-settings.png
  _source/_posts/2019-04-01-spring-boot-microservices-with-kubernetes.md
Labels: qa-complete

#745 Update JHipster 6 post to use CLI for setup
  _source/_assets/img/blog/java-12-jhipster-6/add-claim.png
  _source/_assets/img/blog/java-12-jhipster-6/app-settings.png
  _source/_posts/2019-04-04-java-11-java-12-jhipster-oidc.adoc
  _source/_posts/2019-05-23-java-microservices-spring-cloud-config.adoc
Labels: qa-complete

#747 Update Angular Electron post to use CLI for setup
  _source/_assets/img/blog/angular-electron-browser/new-native-app.png
  _source/_posts/2019-03-20-build-desktop-app-with-angular-electron.md
Labels: qa-complete

#748 Update OAuth 2.0 Guide post with CLI for setup
  _source/_posts/2019-03-12-oauth2-spring-security-guide.md
Labels: qa-complete

#749 Update Spring Microservices HTTP post to use CLI for setup
  _source/_assets/img/blog/microservices-service-to-service-security/oidc-web-app.png
  _source/_posts/2019-03-07-spring-microservices-https-oauth2.adoc
Labels: qa-complete

#750 Update React Auth post to use CLI for setup
  _source/_assets/img/blog/simple-user-auth-react/okta-app-settings.png
  _source/_posts/2019-03-06-simple-user-authentication-in-react.md
Labels: qa-needed

#752 Update Spring Microservices Docker post to use CLI
  _source/_assets/img/blog/spring-microservices-docker/okta-new-web-application-step2.png
  _source/_assets/img/blog/spring-microservices-docker/okta-new-web-application.png
  _source/_posts/2019-02-28-spring-microservices-docker.md
Labels: qa-complete

#751 Update Spring Boot Migration to use CLI for setup
  _source/_assets/img/blog/spring-boot-migration/01_add_oidc_application.png
  _source/_assets/img/blog/spring-boot-migration/02_web_app.png
  _source/_assets/img/blog/spring-boot-migration/03_oidc_app_config.png
  _source/_assets/img/blog/spring-boot-migration/04_clientid_and_secret.png
  _source/_posts/2019-03-05-spring-boot-migration.md
Labels: qa-complete

#753 Update Angular Firebase post to use CLI for setup
  _source/_assets/img/blog/firebase-angular-wiki/okta-settings.png
  _source/_posts/2019-02-28-build-crud-app-with-angular-and-firebase.md
Labels: qa-complete

#756 Update Spring Boot Flyway post to use CLI for setup
  _source/_assets/img/blog/postgresql-with-spring-boot/create-new-service.png
  _source/_assets/img/blog/postgresql-with-spring-boot/create-new-web-application.png
  _source/_assets/img/blog/postgresql-with-spring-boot/service-created.png
  _source/_includes/setup/cli.md
  _source/_posts/2019-02-20-spring-boot-with-postgresql-flyway-jsonb.md
Labels: qa-complete

#754 Update Java i18n post to use CLI for setup
  _source/_assets/img/blog/java-i18n/bootiful-i18n.png
  _source/_posts/2019-02-25-java-i18n-internationalization-localization.adoc
Labels: qa-complete

#755 Update Reactive Spring Boot post to use CLI for setup
  _source/_assets/img/blog/spring-boot-mongodb/create-new-application.png
  _source/_assets/img/blog/spring-boot-mongodb/select-spa.png
  _source/_assets/img/blog/spring-boot-mongodb/spa-with-client-id.png
  _source/_posts/2019-02-21-reactive-with-spring-boot-mongodb.md
Labels: qa-complete

#758 Update Hibernate and Spring post to use CLI for setup
  _source/_assets/img/blog/spring-hibernate-guide/okta-app-general.png
  _source/_assets/img/blog/spring-hibernate-guide/okta-app-wizard-service.png
  _source/_assets/img/blog/spring-hibernate-guide/okta-app-wizard.png
  _source/_posts/2019-02-01-spring-hibernate-guide.md
Labels: qa-complete

#757 Update Social Login post to use CLI for setup
  _source/_assets/img/blog/spring-boot-social-login/add-facebook-idp.png
  _source/_assets/img/blog/spring-boot-social-login/custom-issuer.png
  _source/_assets/img/blog/spring-boot-social-login/customize-domain-name.png
  _source/_assets/img/blog/spring-boot-social-login/customize-signin-page.png
  _source/_assets/img/blog/spring-boot-social-login/identity-providers.png
  _source/_assets/img/blog/spring-boot-social-login/implicit-app.png
  _source/_assets/img/blog/spring-boot-social-login/oidc-app.png
  _source/_posts/2019-02-19-add-social-login-to-spring-boot.md
Labels: qa-complete

#679 Update Laravel Vue post to use CLI for setup
  _source/_assets/img/blog/php-laravel-vue-app/add-application.png
  _source/_assets/img/blog/php-laravel-vue-app/new-spa.png
  _source/_posts/2019-01-15-crud-app-laravel-vue.md
Labels: qa-needed
